aun_pattern: '[user:mail]'
aun_php: 0
aun_update_on_edit: 0
aun_separator: '-'
aun_case: '1'
aun_max_length: '120'
aun_max_component_length: '120'
aun_transliterate: false
aun_reduce_ascii: 0
aun_replace_whitespace: 0
aun_ignore_words: ''
_core:
  default_config_hash: cRB3DSMYqngvGAX0vG3k7WjwHMwWJZDWCOcUtt8xM4E
aun_punctuation_double_quotes: '0'
aun_punctuation_quotes: '0'
aun_punctuation_backtick: '0'
aun_punctuation_comma: '0'
aun_punctuation_period: '0'
aun_punctuation_hyphen: '2'
aun_punctuation_underscore: '2'
aun_punctuation_colon: '0'
aun_punctuation_semicolon: '0'
aun_punctuation_pipe: '0'
aun_punctuation_left_curly: '0'
aun_punctuation_left_square: '0'
aun_punctuation_right_curly: '0'
aun_punctuation_right_square: '0'
aun_punctuation_plus: '0'
aun_punctuation_equal: '0'
aun_punctuation_asterisk: '0'
aun_punctuation_ampersand: '0'
aun_punctuation_percent: '0'
aun_punctuation_caret: '0'
aun_punctuation_dollar: '0'
aun_punctuation_hash: '0'
aun_punctuation_at: '2'
aun_punctuation_exclamation: '0'
aun_punctuation_tilde: '0'
aun_punctuation_left_parenthesis: '0'
aun_punctuation_right_parenthesis: '0'
aun_punctuation_question_mark: '0'
aun_punctuation_less_than: '0'
aun_punctuation_greater_than: '0'
aun_punctuation_slash: '0'
aun_punctuation_back_slash: '0'
