interval: 60000
active_on:
  content_entity_forms: true
  config_entity_forms: true
notification:
  active: true
  message: 'Saving draft...'
  delay: 1000
allowed_content_entity_types:
  block_content:
    bundles:
      basic: basic
  comment:
    bundles:
      comment: comment
  content_moderation_state:
    bundles:
      content_moderation_state: content_moderation_state
  file:
    bundles:
      file: file
  media:
    bundles:
      audio: audio
      document: document
      image: image
      remote_video: remote_video
      video: video
  node:
    bundles:
      article: article
      chc_manufacturer: chc_manufacturer
      chc_vendor: chc_vendor
      chs_products: chs_products
      page: page
      webform: webform
  taxonomy_term:
    bundles:
      chs_healthcare_facility: chs_healthcare_facility
      chs_manufacturer: chs_manufacturer
      chs_product: chs_product
      chs_vendor: chs_vendor
      tags: tags
  webform_submission:
    bundles:
      contact: contact
  menu_link_content:
    bundles:
      menu_link_content: menu_link_content
_core:
  default_config_hash: QnLi3Y7e5T_v9EZqYxRb90E0bBDb2g1y7xREWLKJLC0
