flippy_chc_manufacturer: 0
flippy_head_chc_manufacturer: 0
flippy_show_empty_chc_manufacturer: 0
flippy_prev_label_chc_manufacturer: ''
flippy_next_label_chc_manufacturer: ''
flippy_first_last_chc_manufacturer: 0
flippy_first_label_chc_manufacturer: ''
flippy_last_label_chc_manufacturer: ''
flippy_loop_chc_manufacturer: 0
flippy_random_chc_manufacturer: 0
flippy_random_label_chc_manufacturer: ''
flippy_truncate_chc_manufacturer: ''
flippy_ellipse_chc_manufacturer: ''
flippy_press_swipe_chc_manufacturer: null
flippy_custom_sorting_chc_manufacturer: 0
flippy_sort_chc_manufacturer: nid
flippy_order_chc_manufacturer: ASC
flippy_chc_vendor: 0
flippy_head_chc_vendor: 0
flippy_show_empty_chc_vendor: 0
flippy_prev_label_chc_vendor: ''
flippy_next_label_chc_vendor: ''
flippy_first_last_chc_vendor: 0
flippy_first_label_chc_vendor: ''
flippy_last_label_chc_vendor: ''
flippy_loop_chc_vendor: 0
flippy_random_chc_vendor: 0
flippy_random_label_chc_vendor: ''
flippy_truncate_chc_vendor: ''
flippy_ellipse_chc_vendor: ''
flippy_press_swipe_chc_vendor: null
flippy_custom_sorting_chc_vendor: 0
flippy_sort_chc_vendor: nid
flippy_order_chc_vendor: ASC
flippy_chs_products: 0
flippy_head_chs_products: 0
flippy_show_empty_chs_products: 0
flippy_prev_label_chs_products: ''
flippy_next_label_chs_products: ''
flippy_first_last_chs_products: 0
flippy_first_label_chs_products: ''
flippy_last_label_chs_products: ''
flippy_loop_chs_products: 0
flippy_random_chs_products: 0
flippy_random_label_chs_products: ''
flippy_truncate_chs_products: ''
flippy_ellipse_chs_products: ''
flippy_press_swipe_chs_products: null
flippy_custom_sorting_chs_products: 0
flippy_sort_chs_products: nid
flippy_order_chs_products: ASC
